# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
title: "John Cahill"
title_separator: "-"
subtitle: "Robotics Master's Student & Mechanical Engineer"
name: "John Cahill"
description: "Digital Engineering Portfolio - Specialized in Autonomous Navigation, Manipulation, and Hardware Integration"
url: "https://JackCahill24.github.io"
baseurl: ""
repository: "JackCahill24/JackCahill24.github.io"
masthead_title: "John Cahill"
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: true
copyright: "John Cahill"

# Social Sharing Links
social:
  type: Person
  name: "John Cahill"
  links:
    - https://www.linkedin.com/in/johncahill4493/
    - https://github.com/JackCahill24

# Site Author Profile Sidebar
author:
  name: "John Cahill"
  bio: "Robotics M.S. student at the University of Delaware. Hands-on experience developing autonomous navigation stacks, programming multi-DOF robotic arms, and designing custom mechatronic hardware[cite: 1]."
  location: "Stony Point, NY"[cite: 1]
  email: "johncahill4493@gmail.com"[cite: 1]
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:johncahill4493@gmail.com"[cite: 1]
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/johncahill4493/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JackCahill24"

# Site Footer Links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/johncahill4493/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JackCahill24"
  since: "2026"

# Build configuration rules
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Compiler Engine
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

permalink: /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
